/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transakcje;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JComponent;

/**
 *
 * @author Łukasz Królik
 */
public class PanelTransakcji extends javax.swing.JPanel {

    private ArrayList<Integer> zestawLiczb = new ArrayList<>();

    /**
     * Creates new form PanelTransakcji
     */
    public PanelTransakcji() {

        zestawLiczb.add(1);
        initComponents();
        TablicaTransakcji.addTab("Transakcja: " + String.valueOf(zestawLiczb.get(zestawLiczb.size() - 1)), new Transakcja());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablicaTransakcji = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(TablicaTransakcji, java.awt.BorderLayout.CENTER);

        jButton1.setText("Wciśnij Ctrl + '+' by utworzyć kolejna transakcje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        zestawLiczb.add(znajdzNajmniejszaMozliwaLiczbe());

        TablicaTransakcji.addTab("Transakcja: " + String.valueOf(zestawLiczb.get(zestawLiczb.size() - 1)), new Transakcja());
        TablicaTransakcji.setSelectedIndex(TablicaTransakcji.getComponentCount()-1);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public int znajdzNajmniejszaMozliwaLiczbe() {
        int najmniejsza = 1;
        Collections.sort(zestawLiczb);
        for (int i = 1; i < zestawLiczb.size(); i++) {
            if (i - najmniejsza != 0) {
                najmniejsza = i;

                break;
            }
            najmniejsza = i + 1;
        }
        if (najmniejsza == zestawLiczb.size()) {
            return najmniejsza + 1;
        } else {
            return najmniejsza + 1;
        }
    }

    public void zakonczTransakcje() {
        //TablicaTransakcji.remove(3);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TablicaTransakcji;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
