/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transakcje;

import Klienci.GetClient;
import Towary.MenuTowarow;
import jarex.DaneSklepu;
import jarex.Jarex;
import jarex.MyJPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Łukasz Królik
 */
public class Transakcja extends MyJPanel {

    private int idKarty;
    private Integer IdTransakcji = null;

    /**
     * Creates new form Transakcja
     */
    public Transakcja() {
        initComponents();
        tworzNowaTransakcje();

        try {
            ResultSet rs = DaneSklepu.getConn().createStatement().executeQuery("Select max(id) from transakcje");
            if (rs.next()) {
                this.IdTransakcji = rs.getInt(1);
            }
            DaneSklepu.getConn().setAutoCommit(false);
            DaneSklepu.getConn().commit();
        } catch (SQLException ex) {
            Logger.getLogger(Transakcja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void wyczyscTabele() {
        DefaultTableModel dm = (DefaultTableModel) TransakcjaTable.getModel();
        int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
        for (int i1 = rowCount - 1; i1 >= 0; i1--) {
            dm.removeRow(i1);
        }
    }

    @Override
    public void wypelnijTabele() {

        try {
            DefaultTableModel model = (DefaultTableModel) TransakcjaTable.getModel();
            Statement stmt;
            stmt = DaneSklepu.getConn().createStatement();

            ResultSet rs;
            rs = stmt.executeQuery("select nr_kolejny, t.nazwa, t.cena_zakup, ilosc from towary_w_trans x join towary t on "
                    + "t.kod = x.kod_towaru where id_trans =  " + DaneSklepu.getStrony().get("PanelTransakcji").getCurrentID() + " order by nr_kolejny");

            while (rs.next()) {
                model.addRow(new Object[]{String.valueOf(rs.getInt(1)), rs.getString(2), Double.valueOf(rs.getString(3)), String.valueOf(rs.getInt(4)), Double.valueOf(rs.getString(3)) * rs.getInt(4)});
            }

//            rs = stmt.executeQuery("select sum(cena*ilosc) from towary_w_dost where id = " + String.valueOf(DaneSklepu.getStrony().get("AddDostawa").getCurrentID()));
//            
//            model.addRow(new Object[]{});
//            model.addRow(new Object[]{"", "", "RAZEM : ", rs.getInt(1) });
        } catch (SQLException ex) {
            Logger.getLogger(MenuTowarow.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    public void tworzNowaTransakcje() {
        try {
            //DaneSklepu.getStrony().get("GetTowar").setTransakcja(true);
            Statement stmt = null;
            stmt = DaneSklepu.getConn().createStatement();

            stmt.executeUpdate("Insert into transakcje(id) values (idtrans.NEXTVAL)");

        } catch (SQLException ex) {
            Logger.getLogger(Transakcja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Transakcja(int id, int IDTrans) {
        initComponents();
        this.idKarty = id;
        this.IdTransakcji = IDTrans;
        //tworzNowaTransakcje();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TransakcjaTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(4, 56, 145));

        jButton1.setText("Nowy Towar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Zakończ transakcję");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TransakcjaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TransakcjaTable.setRowHeight(25);
        TransakcjaTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(TransakcjaTable);

        jButton3.setText("Anuluj transakcję");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Usuń towar");

        jButton5.setText("Zmień ilość");

        jButton6.setText("Edytuj cenę /rabat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (getIdTransakcji() == null) {

        }
        try {
            Statement stmt = null;
            stmt = DaneSklepu.getConn().createStatement();
            ResultSet rs = null;
            rs = stmt.executeQuery("select max(nr_kolejny) from towary_w_trans where id_trans = " + getIdTransakcji() + "");
            if (rs.next()) {
                System.out.println("NR KOL: " + rs.getInt(1) + "ID TRANS: " + String.valueOf(DaneSklepu.getStrony().get("PanelTransakcji").getCurrentID()));
                DaneSklepu.getStrony().get("PanelTransakcji").setNrKolejny(rs.getInt(1) + 1);
            }
            DaneSklepu.getStrony().get("GetTowar").setTransakcja(true);
            DaneSklepu.getStrony().get("PanelTransakcji").setCurrentID(getIdTransakcji());

// TODO add your handling code here:
            Jarex.przejdz("GetTowar");
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Transakcja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        JTabbedPane panelTransakcji = (JTabbedPane) SwingUtilities.getAncestorOfClass(JTabbedPane.class, this);
        if (panelTransakcji.getTabCount() > 1) {

            panelTransakcji.remove(this.getIdKarty() - 1);

            PanelTransakcji.getZestawLiczb().remove(Integer.valueOf(this.getIdKarty()));
            try {
                PreparedStatement stmt = null;
                stmt = DaneSklepu.getConn().prepareStatement("Delete from towary_w_trans where id_trans = ?");
                stmt.setInt(1, DaneSklepu.getStrony().get("PanelTransakcji").getCurrentID());
                stmt.executeUpdate();

                stmt = DaneSklepu.getConn().prepareStatement("Delete from transakcje where id = ?");
                stmt.setInt(1, DaneSklepu.getStrony().get("PanelTransakcji").getCurrentID());
                stmt.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(Transakcja.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                
                DaneSklepu.getConn().rollback();
            } catch (SQLException ex) {
                Logger.getLogger(Transakcja.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Jarex.przejdz("PlanszaPoTransakcji");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TransakcjaTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the idKarty
     */
    public int getIdKarty() {
        return idKarty;
    }

    /**
     * @param idKarty the idKarty to set
     */
    public void setIdKarty(int idKarty) {
        this.idKarty = idKarty;
    }

    /**
     * @return the IdTransakcji
     */
    public Integer getIdTransakcji() {
        return IdTransakcji;
    }

    /**
     * @param IdTransakcji the IdTransakcji to set
     */
    public void setIdTransakcji(Integer IdTransakcji) {
        this.IdTransakcji = IdTransakcji;
    }
}
