/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jarex;

/**
 *
 * @author Łukasz Królik
 */
public class MenuPowitalne extends javax.swing.JPanel {
    public boolean manager = false;
    /**
     * Creates new form MenuPowitalne
     */
    public MenuPowitalne() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManagerButton = new javax.swing.JButton();
        SprzedawcaButton = new javax.swing.JButton();

        ManagerButton.setText("Manager");
        ManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerButtonActionPerformed(evt);
            }
        });

        SprzedawcaButton.setText("Sprzedawca");
        SprzedawcaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SprzedawcaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(SprzedawcaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(ManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SprzedawcaButton)
                    .addComponent(ManagerButton))
                .addGap(129, 129, 129))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerButtonActionPerformed

        Jarex.przejdz("MenuStartowe");
       // TODO add your handling code here:
    }//GEN-LAST:event_ManagerButtonActionPerformed

    private void SprzedawcaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SprzedawcaButtonActionPerformed
        Jarex.przejdz("MenuStartowe");
         DaneSklepu.setManagerMode(false);
// TODO add your handling code here:
    }//GEN-LAST:event_SprzedawcaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManagerButton;
    private javax.swing.JButton SprzedawcaButton;
    // End of variables declaration//GEN-END:variables
}
