/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jarex;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import java.awt.*;

/**
 *
 * @author Łukasz Królik
 */
public class MenuStartowe extends javax.swing.JPanel {

    
    /**
     * Creates new form MenuStartowe
     */
    public MenuStartowe() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTransakcjiButton = new javax.swing.JButton();
        TowaryButton = new javax.swing.JButton();
        KlienciButton = new javax.swing.JButton();
        TransakcjeButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        StatystykiButton = new javax.swing.JButton();

        setToolTipText("");

        PanelTransakcjiButton.setText("Okno Sprzedaży");
        PanelTransakcjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelTransakcjiButtonActionPerformed(evt);
            }
        });

        TowaryButton.setText("Towary");
        TowaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TowaryButtonActionPerformed(evt);
            }
        });

        KlienciButton.setText("Klienci");
        KlienciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlienciButtonActionPerformed(evt);
            }
        });

        TransakcjeButton.setText("Dostawy");
        TransakcjeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransakcjeButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Wyjście");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        StatystykiButton.setText("Statystyki");
        StatystykiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatystykiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTransakcjiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TransakcjeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                            .addComponent(StatystykiButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KlienciButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TowaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)))
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTransakcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatystykiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KlienciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TowaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransakcjeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        Jarex.setDoPokazania("MenuPowitalne");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void PanelTransakcjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelTransakcjiButtonActionPerformed
        Jarex.przejdz("PanelTransakcji");        // TODO add your handling code here:
    }//GEN-LAST:event_PanelTransakcjiButtonActionPerformed

    private void StatystykiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatystykiButtonActionPerformed
       Jarex.przejdz("SekcjaStatystyczna"); // TODO add your handling code here:
    }//GEN-LAST:event_StatystykiButtonActionPerformed

    private void TransakcjeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransakcjeButtonActionPerformed
        Jarex.przejdz("MenuDostaw");        // TODO add your handling code here:
    }//GEN-LAST:event_TransakcjeButtonActionPerformed

    private void TowaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TowaryButtonActionPerformed
        Jarex.przejdz("MenuTowarow");// TODO add your handling code here:
    }//GEN-LAST:event_TowaryButtonActionPerformed

    private void KlienciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlienciButtonActionPerformed
        Jarex.przejdz("MenuKlienta");
// TODO add your handling code here:
    }//GEN-LAST:event_KlienciButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KlienciButton;
    private javax.swing.JButton PanelTransakcjiButton;
    private javax.swing.JButton StatystykiButton;
    private javax.swing.JButton TowaryButton;
    private javax.swing.JButton TransakcjeButton;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
