/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jarex;

import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JApplet;
import javax.swing.JOptionPane;

/**
 *
 * @author Łukasz Królik
 */
public class PasekGorny extends javax.swing.JPanel {

    /**
     * Creates new form PasekGorny
     */
    public PasekGorny() {
        GraphicsEnvironment graphicsEnvironment = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle maximumWindowBounds = graphicsEnvironment.getMaximumWindowBounds();
        setLayout(new java.awt.FlowLayout(200));

        setBounds(0, 0, (int) maximumWindowBounds.getX(), 30);

        initComponents();
        setTime();

    }

    public void setTime() {
        Date dNow = new Date();
        SimpleDateFormat ft
                = new SimpleDateFormat("E dd.MM.yyyy    kk:mm:ss");

        DataLabel.setText("          Data: " + ft.format(dNow));
    }

    public void setMode() {

        if (DaneSklepu.isManagerMode() == true) {
            TrybLabel.setText("Tryb : Manager");
                    
        } else {
            TrybLabel.setText("Tryb : Sprzedawca");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WsteczButton = new javax.swing.JButton();
        SprzedazButton = new javax.swing.JButton();
        TowaryButton = new javax.swing.JButton();
        KlienciButton = new javax.swing.JButton();
        DostawyButton = new javax.swing.JButton();
        TransakcjaButton = new javax.swing.JButton();
        HistoriaButton = new javax.swing.JButton();
        PowitalnyButton = new javax.swing.JButton();
        TrybLabel = new javax.swing.JLabel();
        DataLabel = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 32, 84));
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N

        WsteczButton.setText("Wstecz");
        WsteczButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WsteczButtonActionPerformed(evt);
            }
        });
        add(WsteczButton);

        SprzedazButton.setText("Sprzedaż");
        SprzedazButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SprzedazButtonActionPerformed(evt);
            }
        });
        add(SprzedazButton);

        TowaryButton.setText("Towary");
        TowaryButton.setMaximumSize(new java.awt.Dimension(69, 25));
        TowaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TowaryButtonActionPerformed(evt);
            }
        });
        add(TowaryButton);

        KlienciButton.setText("Klienci");
        KlienciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlienciButtonActionPerformed(evt);
            }
        });
        add(KlienciButton);

        DostawyButton.setText("Dostawy");
        DostawyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DostawyButtonActionPerformed(evt);
            }
        });
        add(DostawyButton);

        TransakcjaButton.setText("Transakcje");
        TransakcjaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransakcjaButtonActionPerformed(evt);
            }
        });
        add(TransakcjaButton);

        HistoriaButton.setText("Historia");
        HistoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoriaButtonActionPerformed(evt);
            }
        });
        add(HistoriaButton);

        PowitalnyButton.setText("Wybór trybu");
        PowitalnyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowitalnyButtonActionPerformed(evt);
            }
        });
        add(PowitalnyButton);

        TrybLabel.setForeground(new java.awt.Color(255, 255, 255));
        TrybLabel.setText("Tryb : ");
        add(TrybLabel);

        DataLabel.setForeground(new java.awt.Color(255, 255, 255));
        DataLabel.setText("Data : ");
        add(DataLabel);

        ExitButton.setText("Wyjście");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        add(ExitButton);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void PowitalnyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowitalnyButtonActionPerformed
        
        Jarex.przejdz("MenuPowitalne");
// TODO add your handling code here:
    }//GEN-LAST:event_PowitalnyButtonActionPerformed

    private void WsteczButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WsteczButtonActionPerformed
        
        if (DaneSklepu.getStos().size() > 0){
            DaneSklepu.setWsteczButton(true);
        Jarex.przejdz((String) DaneSklepu.getStos().pollLast());
        }
        else
            JOptionPane.showMessageDialog(this, "Nie robiłeś nic wcześniej", "Błąd", 0);
        
//String s = 
// TODO add your handling code here:
    }//GEN-LAST:event_WsteczButtonActionPerformed

    private void TransakcjaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransakcjaButtonActionPerformed
        Jarex.przejdz("MenuTransakcji");        // TODO add your handling code here:
    }//GEN-LAST:event_TransakcjaButtonActionPerformed

    private void TowaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TowaryButtonActionPerformed
        Jarex.przejdz("MenuTowarow");// TODO add your handling code here:
    }//GEN-LAST:event_TowaryButtonActionPerformed

    private void KlienciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlienciButtonActionPerformed
        Jarex.przejdz("MenuKlienta");// TODO add your handling code here:
    }//GEN-LAST:event_KlienciButtonActionPerformed

    private void DostawyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DostawyButtonActionPerformed
        Jarex.przejdz("MenuDostaw");// TODO add your handling code here:
    }//GEN-LAST:event_DostawyButtonActionPerformed

    private void HistoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoriaButtonActionPerformed
        Jarex.przejdz("SekcjaStatystyczna");// TODO add your handling code here:
    }//GEN-LAST:event_HistoriaButtonActionPerformed

    private void SprzedazButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SprzedazButtonActionPerformed
        Jarex.przejdz("PanelTransakcji");// TODO add your handling code here:
    }//GEN-LAST:event_SprzedazButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataLabel;
    private javax.swing.JButton DostawyButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HistoriaButton;
    private javax.swing.JButton KlienciButton;
    private javax.swing.JButton PowitalnyButton;
    private javax.swing.JButton SprzedazButton;
    private javax.swing.JButton TowaryButton;
    private javax.swing.JButton TransakcjaButton;
    private javax.swing.JLabel TrybLabel;
    private javax.swing.JButton WsteczButton;
    // End of variables declaration//GEN-END:variables
}
