/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Towary;

import Klienci.MenuKlienta;
import jarex.DaneSklepu;
import jarex.MyJPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Łukasz Królik
 */
public class MenuTowarow extends MyJPanel {

    /**
     * Creates new form MenuTowarow
     */
    public MenuTowarow() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablicaTowar = new javax.swing.JTable();

        jButton2.setText("Przeglądaj listę towarów do zamówienia");

        jButton3.setText("Przyjmij nową dostawę");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Dodaj nowy towar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Edytuj towar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Usuń towar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        TablicaTowar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TablicaTowar.setRowHeight(25);
        jScrollPane2.setViewportView(TablicaTowar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (TablicaTowar.getSelectedRow() >0) {
            JTextField nazwa = new JTextField();
            JTextField cena = new JTextField();
            JTextField cena_dost = new JTextField();

            Object[] message = {
                "Nazwa produktu:", nazwa,
                "Cena sprzedaży:", cena,
                "Cena dostawy:", cena_dost,};
            String idText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 0);
            String nazwaText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 1);
            String cenaText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 2);
            String cenaDostText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 3);

            nazwa.setText(nazwaText);
            cena.setText(cenaText);
            cena_dost.setText(cenaDostText);

            PreparedStatement stmt = null;
            UIManager.put("OptionPane.cancelButtonText", "Anuluj");
            int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);

            if (option == JOptionPane.OK_OPTION) {
                try {
                    stmt = DaneSklepu.getConn().prepareStatement("Update towary set nazwa = ?, cena_zakup = ?, cena_zamow = ? where kod = " + idText);
                    stmt.setString(1, nazwa.getText());
                    stmt.setDouble(2, Double.valueOf(cena.getText()));
                    stmt.setDouble(3, Double.valueOf(cena_dost.getText()));

                    stmt.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(MenuKlienta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            wyczyscTabele();
            wypelnijTabele();

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jarex.Jarex.przejdz("AddDostawa");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JTextField nazwa = new JTextField();
        JTextField cena = new JTextField();
        JTextField cena_dost = new JTextField();

        Object[] message = {
            "Nazwa produktu:", nazwa,
            "Cena sprzedaży:", cena,
            "Cena dostawy:", cena_dost,};

        PreparedStatement stmt = null;
        UIManager.put("OptionPane.cancelButtonText", "Anuluj");
        int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            try {
                stmt = DaneSklepu.getConn().prepareStatement("Insert into towary(kod, nazwa, cena_zakup, cena_zamow, DO_ZAMOWIENIA) values (idtowar.NEXTVAL , ? , ? , ?, 'TAK')");
                stmt.setString(1, nazwa.getText());
                stmt.setDouble(2, Double.valueOf(cena.getText()));
                stmt.setDouble(3, Double.valueOf(cena_dost.getText()));

                stmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(MenuKlienta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        wyczyscTabele();
        wypelnijTabele();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        if (TablicaTowar.getSelectedRow() > 0) {
            
            String idText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 0);
            String nazwaText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 1);
            String cenaText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 2);
            String cenaDostText = (String) TablicaTowar.getValueAt(TablicaTowar.getSelectedRow(), 3);

            
            PreparedStatement stmt = null;
            UIManager.put("OptionPane.cancelButtonText", "Anuluj");
            int option = JOptionPane.showConfirmDialog(null, "Czy usunąć towar: " + nazwaText, "Potwierdzenie", JOptionPane.OK_CANCEL_OPTION);

            if (option == JOptionPane.OK_OPTION) {
                try {
                    stmt = DaneSklepu.getConn().prepareStatement("Delete from towary where kod = " + idText);
                    
                    stmt.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(MenuKlienta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            wyczyscTabele();
            wypelnijTabele();

        }

    }//GEN-LAST:event_jButton6ActionPerformed

    @Override
    public void wyczyscTabele() {
        DefaultTableModel dm = (DefaultTableModel) TablicaTowar.getModel();
        int rowCount = dm.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }

    @Override
    public void wypelnijTabele() {
        try {

            DefaultTableModel model = (DefaultTableModel) TablicaTowar.getModel();

            Statement stmt;
            stmt = DaneSklepu.getConn().createStatement();

            ResultSet rs;
            rs = stmt.executeQuery("select kod, nazwa, cena_zakup, cena_zamow, ilosc_w_magazynie, "
                    + "do_zamowienia, rabat from towary where kod > 0 order by kod");

            while (rs.next()) {
                model.addRow(new Object[]{String.valueOf(rs.getInt(1)), rs.getString(2), String.valueOf(rs.getDouble(3)), String.valueOf(rs.getDouble(4)),
                    String.valueOf(rs.getInt(5)), rs.getString(6)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuTowarow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablicaTowar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
